version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    volumes:
      - ../:/app
      - ../config/test.ini:/automation_ui_playwright_pytest/config/test.ini
      - ../config/uat.ini:/automation_ui_playwright_pytest/config/uat.ini
      - ../config/prod.ini:/automation_ui_playwright_pytest/config/prod.ini
    command: tail -f /dev/null
    environment:
      - ENV=dev
    ports:
      - '9170:9170'