name: ci-workflow

on:
  workflow_run:
    workflows: [ 'infra-workflow' ]
    types:
      - completed
  pull_request:
    paths-ignore: ['deployment/terraform/**']
  push:
    branches: [master]
    paths-ignore: ['deployment/terraform/**']

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      POETRY_VIRTUALENVS_CREATE: false

    steps:
      - name: checkout-code
        uses: actions/checkout@v4
      - name: setup-python-for-ut
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: install-poetry
        run: make install-poetry
      - name: install-dependencies
        run: make install-playwright-chromium
      - name: run-unit-test
        run: pytest --env=test -s -v test_suite/z_repo_unit
