name: deploy-to-cloud-run

on:
  workflow_run:
    workflows: ['ci-workflow']
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: setup-tereform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: terraform-init
        run: make terraform-init

      - name: terraform-apply
        run: make terraform-apply
