name: deploy-to-cloud-run

on:
  workflow_run:
    workflows: ['ci-workflow']
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: auth-google-cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: setup-google-cli
        uses: google-github-actions/setup-gcloud@v1

      - name: auth-docker-to-artifact-registry
        run: make gcloud-auth-docker-to-artifact-registry

      - name: setup-tereform
        uses: hashicorp/setup-terraform@v3

      - name: terraform-init
        run: make terraform-init

      - name: terraform-apply
        run: make terraform-apply
        env:
          GCP_CREDENTIALS_PATH: ${{ steps.auth-google-cloud.outputs.credentials_file_path }}
