name: deploy-cloudrun

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup-terraform
        uses: hashicorp/setup-terraform@v3

      - name: deploy-to-cloud-run
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          make terraform-init
          make terraform-apply
